[2022-08-04 12:27:53,151] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: secret_vars.test_conn manual__2022-08-04T09:27:46.287052+00:00 [queued]>
[2022-08-04 12:27:53,153] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: secret_vars.test_conn manual__2022-08-04T09:27:46.287052+00:00 [queued]>
[2022-08-04 12:27:53,153] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 12:27:53,153] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-04 12:27:53,153] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 12:27:53,159] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): test_conn> on 2022-08-04 09:27:46.287052+00:00
[2022-08-04 12:27:53,161] {standard_task_runner.py:52} INFO - Started process 62244 to run task
[2022-08-04 12:27:53,163] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'secret_vars', 'test_conn', 'manual__2022-08-04T09:27:46.287052+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/task_dag.py', '--cfg-path', '/tmp/tmpg8tthjwd', '--error-file', '/tmp/tmpbkq_25go']
[2022-08-04 12:27:53,163] {standard_task_runner.py:80} INFO - Job 43: Subtask test_conn
[2022-08-04 12:27:53,182] {task_command.py:371} INFO - Running <TaskInstance: secret_vars.test_conn manual__2022-08-04T09:27:46.287052+00:00 [running]> on host ndx-Victus
[2022-08-04 12:27:53,203] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=secret_vars
AIRFLOW_CTX_TASK_ID=test_conn
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T09:27:46.287052+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-04T09:27:46.287052+00:00
[2022-08-04 12:27:53,205] {base.py:68} INFO - Using connection ID 'mongo_test_hook' for task execution.
[2022-08-04 12:27:54,180] {logging_mixin.py:115} INFO - Replace 0
[2022-08-04 12:27:54,264] {logging_mixin.py:115} INFO - Replace 100
[2022-08-04 12:27:54,351] {logging_mixin.py:115} INFO - Replace 200
[2022-08-04 12:27:54,444] {logging_mixin.py:115} INFO - Replace 300
[2022-08-04 12:27:54,545] {logging_mixin.py:115} INFO - Replace 400
[2022-08-04 12:27:54,646] {logging_mixin.py:115} INFO - Replace 500
[2022-08-04 12:27:54,755] {logging_mixin.py:115} INFO - Replace 600
[2022-08-04 12:27:54,869] {logging_mixin.py:115} INFO - Replace 700
[2022-08-04 12:27:54,987] {logging_mixin.py:115} INFO - Replace 800
[2022-08-04 12:27:55,111] {logging_mixin.py:115} INFO - Replace 900
[2022-08-04 12:27:55,241] {logging_mixin.py:115} INFO - Replace 1000
[2022-08-04 12:27:55,377] {logging_mixin.py:115} INFO - Replace 1100
[2022-08-04 12:27:55,518] {logging_mixin.py:115} INFO - Replace 1200
[2022-08-04 12:27:55,663] {logging_mixin.py:115} INFO - Replace 1300
[2022-08-04 12:27:55,814] {logging_mixin.py:115} INFO - Replace 1400
[2022-08-04 12:27:55,972] {logging_mixin.py:115} INFO - Replace 1500
[2022-08-04 12:27:56,134] {logging_mixin.py:115} INFO - Replace 1600
[2022-08-04 12:27:56,303] {logging_mixin.py:115} INFO - Replace 1700
[2022-08-04 12:27:56,476] {logging_mixin.py:115} INFO - Replace 1800
[2022-08-04 12:27:56,655] {logging_mixin.py:115} INFO - Replace 1900
[2022-08-04 12:27:56,838] {logging_mixin.py:115} INFO - Replace 2000
[2022-08-04 12:27:57,026] {logging_mixin.py:115} INFO - Replace 2100
[2022-08-04 12:27:57,220] {logging_mixin.py:115} INFO - Replace 2200
[2022-08-04 12:27:57,420] {logging_mixin.py:115} INFO - Replace 2300
[2022-08-04 12:27:57,626] {logging_mixin.py:115} INFO - Replace 2400
[2022-08-04 12:27:57,839] {logging_mixin.py:115} INFO - Replace 2500
[2022-08-04 12:27:58,053] {logging_mixin.py:115} INFO - Replace 2600
[2022-08-04 12:27:58,274] {logging_mixin.py:115} INFO - Replace 2700
[2022-08-04 12:27:58,498] {logging_mixin.py:115} INFO - Replace 2800
[2022-08-04 12:27:58,728] {logging_mixin.py:115} INFO - Replace 2900
[2022-08-04 12:27:58,961] {logging_mixin.py:115} INFO - Replace 3000
[2022-08-04 12:27:59,199] {logging_mixin.py:115} INFO - Replace 3100
[2022-08-04 12:27:59,442] {logging_mixin.py:115} INFO - Replace 3200
[2022-08-04 12:27:59,697] {logging_mixin.py:115} INFO - Replace 3300
[2022-08-04 12:27:59,961] {logging_mixin.py:115} INFO - Replace 3400
[2022-08-04 12:28:00,227] {logging_mixin.py:115} INFO - Replace 3500
[2022-08-04 12:28:00,496] {logging_mixin.py:115} INFO - Replace 3600
[2022-08-04 12:28:00,619] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 62244. PIDs of all processes in the group: [62244]
[2022-08-04 12:28:00,619] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 62244
[2022-08-04 12:28:00,619] {taskinstance.py:1561} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-08-04 12:28:00,622] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/task_dag.py", line 19, in test_conn
    hook(mongo_collection="users", db_name="test")
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/mongo_inserter.py", line 29, in __call__
    if super().find(mongo_collection=mongo_collection, \
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/mongo_hook.py", line 139, in find
    return collection.find_one(query, projection, **kwargs)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/collection.py", line 1452, in find_one
    for result in cursor.limit(-1):
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/cursor.py", line 1112, in __send_message
    self.close()
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/cursor.py", line 434, in close
    self.__die(True)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/cursor.py", line 420, in __die
    self.__collection.database.client._cleanup_cursor(
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1557, in _cleanup_cursor
    session._end_session(lock=locks_allowed)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/client_session.py", line 510, in _end_session
    self._client._return_server_session(self._server_session, lock)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1702, in _return_server_session
    return self._topology.return_server_session(server_session, lock)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/topology.py", line 572, in return_server_session
    self._session_pool.return_server_session(
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/client_session.py", line 1097, in return_server_session
    self.return_server_session_no_lock(server_session)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/client_session.py", line 1099, in return_server_session_no_lock
    def return_server_session_no_lock(self, server_session):
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1563, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-08-04 12:28:00,624] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=secret_vars, task_id=test_conn, execution_date=20220804T092746, start_date=20220804T092753, end_date=20220804T092800
[2022-08-04 12:28:00,629] {standard_task_runner.py:92} ERROR - Failed to execute job 43 for task test_conn (Task received SIGTERM signal; 62244)
[2022-08-04 12:28:00,645] {process_utils.py:75} INFO - Process psutil.Process(pid=62244, status='terminated', exitcode=1, started='12:27:53') (62244) terminated with exit code 1
